title: Carlos A.Taimal
description: "Data Science & Everything in between"
url: "https://c-taimal.github.io"
baseurl: ""
permalink: /:slug.html

favicon: "logo.png"

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: false
  lowercase_titles: true

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

kramdown:
  input: GFM
  math_engine: mathjax